1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota
* El array de 2 dimensiones debe ser de 2 filas y 3 columnas
* El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [2]:
import numpy as np

In [3]:
a1 = np.random.rand(2)
a2 = np.random.rand(2,3)
a3 = np.random.rand(2,3,5)

In [4]:
a1

array([0.42149357, 0.82407824])

In [5]:
a2

array([[0.80843375, 0.07077994, 0.02429875],
       [0.69214198, 0.52905165, 0.78787878]])

In [6]:
a3

array([[[0.23379052, 0.44807524, 0.24444094, 0.11412444, 0.82854217],
        [0.94291905, 0.3354447 , 0.90919066, 0.11902033, 0.95090266],
        [0.88066322, 0.40384868, 0.02485785, 0.24791155, 0.32691974]],

       [[0.75161743, 0.54157565, 0.96234186, 0.93045949, 0.71236742],
        [0.37676018, 0.44735072, 0.69769846, 0.12894291, 0.95927633],
        [0.5642161 , 0.53822724, 0.83734088, 0.56779887, 0.80224642]]])

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [7]:
# forma
a1.shape

(2,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 5)

In [10]:
# tamaño (número de elementos)
a1.size

2

In [11]:
a2.size

6

In [12]:
a3.size

30

In [13]:
# dimensiones
a1.ndim

1

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [16]:
# tipo de datos que contienen
a1.dtype

dtype('float64')

In [17]:
a2.dtype

dtype('float64')

In [18]:
a3.dtype

dtype('float64')

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [22]:
a_id = np.identity(3)
a_id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [23]:
a_ones = np.ones_like(a_id)
a_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

5. Es el momento de hacer algunas operaciones entre arrays
* ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

In [ ]:
# no se pueden sumar, porque no tienen la misma forma 'ValueError: operands could not be broadcast together with shapes (2,3) (3,3)'

In [24]:
a2 + a_id

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
suma = np.add(a2, a_id)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

* En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [25]:
a4 = np.ones_like(a_id)
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
a4 + a_id

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

* Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [27]:
a_id * a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.multiply(a_id, a4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#EXTRA
# probamos a multiplicar a_id con la matriz a2
a_id * a2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
# probamos lo que dijimios en clase:
# si coinciden el numero de columnas de a_id con el numero de filas de otra matriz, ¿se pueden multiplicar?


ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [ ]:
# creamos nueva matriz con el mismo numero de filas que columnas tiene a_id
a5 = np.random.rand(3,4)
a5

array([[0.77752464, 0.12329757, 0.53787145, 0.28726463],
       [0.37326012, 0.4497301 , 0.27676603, 0.05010867],
       [0.09026727, 0.76457882, 0.01356508, 0.71969869]])

In [ ]:
a_id * a5

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [ ]:
# ¿y al reves?
a5 * a_id

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [ ]:
# CONCLUSION lo que dijimos en clase no está funcionando

* Dividid las dos matrices

In [ ]:
a_id / a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.divide(a_id, a4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])