1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota
* El array de 2 dimensiones debe ser de 2 filas y 3 columnas
* El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [1]:
import numpy as np

In [2]:
a1 = np.random.rand(2)
a2 = np.random.rand(2,3)
a3 = np.random.rand(2,3,5)

In [9]:
a1

array([0.23794398, 0.89596957])

In [10]:
a2

array([[0.84427896, 0.42713293, 0.2403992 ],
       [0.19622559, 0.89902999, 0.46279634]])

In [11]:
a3

array([[[0.54956037, 0.93661088, 0.86115263, 0.27887598, 0.79460509],
        [0.96682806, 0.70788586, 0.56673781, 0.02876703, 0.45474784],
        [0.77569606, 0.75694025, 0.76904709, 0.86760802, 0.36829641]],

       [[0.69686886, 0.95106639, 0.26660697, 0.96096594, 0.23913626],
        [0.83429363, 0.0585109 , 0.07605626, 0.39943377, 0.63622268],
        [0.48710082, 0.38180619, 0.93060674, 0.37983857, 0.31672528]]])

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [4]:
# forma
a1.shape

(2,)

In [3]:
a2.shape

(2, 3)

In [5]:
a3.shape

(2, 3, 5)

In [6]:
# tamaño (número de elementos)
a1.size

2

In [7]:
a2.size

6

In [8]:
a3.size

30

In [12]:
# dimensiones
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

In [15]:
# tipo de datos que contienen
a1.dtype

dtype('float64')

In [16]:
a2.dtype

dtype('float64')

In [17]:
a3.dtype

dtype('float64')

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [19]:
a_id= np.identity(2,3)
a_id
# una matriz identidad solo puede ser de máximo dos dimensiones

TypeError: Cannot interpret '3' as a data type

In [21]:
a_id = np.identity(3)
a_id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [23]:
a_ones = np.ones_like(a_id)
a_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

5. Es el momento de hacer algunas operaciones entre arrays
* ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

In [24]:
a2 + a_id

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [25]:
suma = np.add(a2, a_id)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
# no se pueden sumar, porque no tienen la misma forma 'ValueError: operands could not be broadcast together with shapes (2,3) (3,3)'

* En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [26]:
a4 = np.ones_like(a_id)
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a4 + a_id

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

* Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [28]:
a_id * a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.multiply(a_id, a4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#EXTRA
# probamos a multiplicar a_id con la matriz a2
a_id * a2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [35]:
# probamos lo que dijimios en clase:
# si coinciden el numero de columnas de a_id con el numero de filas de otra matriz, ¿se pueden multiplicar?


ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [34]:
# creamos nueva matriz con el mismo numero de filas que columnas tiene a_id
a5 = np.random.rand(3,4)
a5

array([[0.77752464, 0.12329757, 0.53787145, 0.28726463],
       [0.37326012, 0.4497301 , 0.27676603, 0.05010867],
       [0.09026727, 0.76457882, 0.01356508, 0.71969869]])

In [39]:
a_id * a5

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [36]:
# ¿y al reves?
a5 * a_id

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [ ]:
# CONCLUSION lo que dijimos en clase no está funcionando

* Dividid las dos matrices

In [37]:
a_id / a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.divide(a_id, a4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])