1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [1]:
import numpy as np

In [2]:
np.random.seed(7)
a1 = np.random.random_sample((5,6))


In [28]:
np.random.seed(8)
a2 = np.random.random_sample((5,6))

In [29]:
a1

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951,
        0.53849587],
       [0.50112046, 0.07205113, 0.26843898, 0.4998825 , 0.67923   ,
        0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353, 0.21338535,
        0.45212396],
       [0.93120602, 0.02489923, 0.60054892, 0.9501295 , 0.23030288,
        0.54848992],
       [0.90912837, 0.13316945, 0.52341258, 0.75040986, 0.66901324,
        0.46775286]])

In [30]:
a2

array([[0.8734294 , 0.96854066, 0.86919454, 0.53085569, 0.23272833,
        0.0113988 ],
       [0.43046882, 0.40235136, 0.52267467, 0.4783918 , 0.55535647,
        0.54338602],
       [0.76089558, 0.71237457, 0.6196821 , 0.42609177, 0.28907503,
        0.97385524],
       [0.33377405, 0.21880106, 0.06580839, 0.98287055, 0.12785571,
        0.32213079],
       [0.07094284, 0.22476994, 0.39363491, 0.896145  , 0.34546161,
        0.98474944]])

2. Cread los siguientes arrays:
* Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [31]:
a_uni = np.round(np.random.uniform(0,10, size = (2,3,5)), 0)
a_uni

array([[[ 0.,  4.,  4.,  8.,  9.],
        [ 3.,  4.,  3.,  8.,  6.],
        [ 1.,  6.,  8.,  0.,  5.]],

       [[ 8., 10.,  6.,  0.,  4.],
        [ 2.,  6.,  2.,  2.,  5.],
        [ 1.,  7.,  9.,  9.,  4.]]])

* Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [32]:
a_bi = np.random.binomial(10, 0.3, size = (2,3,5))
a_bi

array([[[3, 4, 3, 3, 0],
        [1, 3, 3, 2, 3],
        [3, 4, 2, 3, 4]],

       [[3, 4, 3, 4, 4],
        [5, 2, 2, 3, 3],
        [3, 4, 3, 5, 4]]])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
* Elementos comunes entre los dos arrays

In [33]:
np.intersect1d(a_uni, a_bi, return_indices=True)
#el primer array nos devuelve los elementos comunes
#el segundo array los indices de los elementos comunes en el a_uni
#en el tercer array estan los indices de los elementos comunes del a_bi

(array([0., 1., 2., 3., 4., 5.]),
 array([ 0, 10, 20,  5,  1, 14]),
 array([ 4,  5,  8,  0,  1, 20]))

* Unión de los dos arrays

In [34]:
np.union1d(a_uni, a_bi)
# nos devuelve un array con todos los valares unicos de los dos arrays

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

* ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [35]:
np.setdiff1d(a_uni, a_bi) 
#nos devuelve los elementos que estan en el a_uni pero no en a_bi

array([ 6.,  7.,  8.,  9., 10.])

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [36]:
array1 = np.random.randint(1,100, 80)
array1

array([25, 98, 33, 25, 80, 42, 15, 78, 86, 61, 11,  3, 30, 95,  3, 13, 99,
       72,  8, 72, 55, 62, 11, 36, 51, 16, 53, 82, 71, 52, 20, 49, 69, 41,
       64, 69, 87, 45, 49, 99, 68, 30, 75, 47, 90,  7, 91, 77, 75, 59, 29,
       51, 13, 87, 28, 82, 82, 74, 20, 48, 93, 97, 99, 25, 65, 82, 45, 52,
       99, 40, 77, 86, 34, 66, 71, 58, 89, 33, 22, 37])

In [37]:
array2 = np.random.randint(1,100, 80)
array2

array([73, 18, 87,  1,  7, 21,  6, 46,  2, 82, 15, 34, 83, 84, 39, 16, 20,
       15, 44, 52, 85, 43, 81, 85, 88,  7, 44, 42, 24,  9, 50, 71, 91, 83,
       78,  2, 12, 78,  5, 85, 27, 63, 22, 43, 22, 13, 91, 76, 85, 72, 29,
       96, 51, 49, 94, 20, 32,  2,  5, 30, 60,  3, 95, 74, 94, 36, 46, 61,
       35, 62, 33, 89, 53, 60, 36, 82, 10, 89, 66, 58])

* Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [38]:
array1 = np.unique(array1)
array1

array([ 3,  7,  8, 11, 13, 15, 16, 20, 22, 25, 28, 29, 30, 33, 34, 36, 37,
       40, 41, 42, 45, 47, 48, 49, 51, 52, 53, 55, 58, 59, 61, 62, 64, 65,
       66, 68, 69, 71, 72, 74, 75, 77, 78, 80, 82, 86, 87, 89, 90, 91, 93,
       95, 97, 98, 99])

In [39]:
array1.size

55

In [40]:
array2 = np.unique(array2)
array2

array([ 1,  2,  3,  5,  6,  7,  9, 10, 12, 13, 15, 16, 18, 20, 21, 22, 24,
       27, 29, 30, 32, 33, 34, 35, 36, 39, 42, 43, 44, 46, 49, 50, 51, 52,
       53, 58, 60, 61, 62, 63, 66, 71, 72, 73, 74, 76, 78, 81, 82, 83, 84,
       85, 87, 88, 89, 91, 94, 95, 96])

In [41]:
array2.size

59

* Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [42]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 8, 11, 25, 28, 37, 40, 41, 45, 47, 48, 55, 59, 64, 65, 68, 69, 75,
       77, 80, 86, 90, 93, 97, 98, 99])

* Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [43]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 1,  2,  5,  6,  9, 10, 12, 18, 21, 24, 27, 32, 35, 39, 43, 44, 46,
       50, 60, 63, 73, 76, 81, 83, 84, 85, 88, 94, 96])

* Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [44]:
array5 = np.intersect1d(array1, array2)
array5

array([ 3,  7, 13, 15, 16, 20, 22, 29, 30, 33, 34, 36, 42, 49, 51, 52, 53,
       58, 61, 62, 66, 71, 72, 74, 78, 82, 87, 89, 91, 95])

* ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [45]:
# arr1 y arr2 fueron creados de forma aleatoria con las mismas condiciones.
# Al crear los nuevos arrays con np.unique(arr1 y arr2), se ve que arr 1 tenía más elementos repetidos que  arr2, ya que --> array1.size > array2.size

In [65]:
print('La cantidad de elementos únicos que tiene arr1 son:', array1.size)
print('La cantidad de elementos únicos que tiene arr2 son:', array2.size)
print('arr2 tiene', (array2.size) - (array1.size), 'elementos únicos más que arr1')
print('Por eso ¿Es array 2 más grande que array1?: ', array2.size > array1.size)

La cantidad de elementos únicos que tiene arr1 son: 55
La cantidad de elementos únicos que tiene arr2 son: 59
arr2 tiene 4 elementos únicos más que arr1
Por eso ¿Es array 2 más grande que array1?:  True


In [49]:
# El array3 contiene los elementos diferentes que tiene el array1 con respecto al array2. Osea los que solo están en array1
# El array4 contiene los elementos diferentes que tiene el array2 con respecto al array1. Osea los que solo están en array2

In [48]:
array3.size

25

In [50]:
array4.size

29

In [60]:
print('El array 3 es la diferencia entre array 1 y array 2.\n El array 1 tiene', array3.size, 'elementos distintos con respecto a array 2.')

El array 3 es la diferencia entre array 1 y array 2.
 El array 1 tiene 25 elementos distintos con respecto a array2.


In [61]:
print('El array 4 es la diferencia entre array 2 y array 1.\n El array 2 tiene', array4.size, 'elementos distintos con respecto a array 1.')

El array 4 es la diferencia entre array 2 y array 1.
 El array 2 tiene 29 elementos distintos con respecto a array 1.


In [58]:
print('El array 5 es la intersección de array 1 y array 2.\n Tienen', array5.size, 'elementos en común.')

El array 5 es la intersección de array 1 y array 2.
 Tienen 30 elementos en común.


In [57]:
print('La suma de las longitudes de array 5 + array 3 es:', array5.size + array3.size, '\n Que es igual al tamaño original de array 1:', array1.size)

La suma de las longitudes de array 5 + array 3 es: 55 
 Que es igual al tamaño original de array 1: 55


In [55]:
print('La suma de las longitudes de array 5 + array 4 es:', array5.size + array4.size, '\n Que es igual al tamaño original de array 2:', array2.size)

La suma de las longitudes de array 5 + array 4 es: 59 
 Que es igual al tamaño original de array 2: 59
