1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [1]:
import numpy as np

In [8]:
np.random.seed(7)
a1 = np.random.random_sample((5,6))


In [10]:
np.random.seed(7)
a2 = np.random.random_sample((5,6))

In [9]:
a1

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951,
        0.53849587],
       [0.50112046, 0.07205113, 0.26843898, 0.4998825 , 0.67923   ,
        0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353, 0.21338535,
        0.45212396],
       [0.93120602, 0.02489923, 0.60054892, 0.9501295 , 0.23030288,
        0.54848992],
       [0.90912837, 0.13316945, 0.52341258, 0.75040986, 0.66901324,
        0.46775286]])

In [11]:
a2

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951,
        0.53849587],
       [0.50112046, 0.07205113, 0.26843898, 0.4998825 , 0.67923   ,
        0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353, 0.21338535,
        0.45212396],
       [0.93120602, 0.02489923, 0.60054892, 0.9501295 , 0.23030288,
        0.54848992],
       [0.90912837, 0.13316945, 0.52341258, 0.75040986, 0.66901324,
        0.46775286]])

2. Cread los siguientes arrays:
* Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [14]:
a_uni = np.round(np.random.uniform(0,10, size = (2,3,5)), 0)
a_uni

array([[[2., 5., 4., 5., 4.],
        [8., 8., 3., 6., 3.],
        [5., 4., 7., 4., 5.]],

       [[7., 4., 9., 2., 7.],
        [4., 4., 6., 5., 4.],
        [0., 1., 7., 5., 7.]]])

* Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [18]:
a_bi = np.random.binomial(10, 0.3, size = (2,3,5))
a_bi

array([[[0, 3, 4, 3, 1],
        [2, 3, 5, 7, 2],
        [0, 4, 5, 3, 4]],

       [[5, 3, 5, 0, 2],
        [2, 1, 5, 1, 4],
        [1, 2, 3, 2, 3]]])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
* Elementos comunes entre los dos arrays

In [23]:
np.intersect1d(a_uni, a_bi, return_indices=True)

(array([0., 1., 2., 3., 4., 5., 7.]),
 array([25, 26,  0,  7,  2,  1, 12]),
 array([0, 4, 5, 1, 2, 7, 8]))

* Unión de los dos arrays

In [24]:
np.union1d(a_uni, a_bi)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

* ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [25]:
np.setdiff1d(a_uni, a_bi) 

array([6., 8., 9.])

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [30]:
array1 = np.random.randint(1,100, 80)
array1

array([11, 74, 85, 80, 81, 63, 26,  2, 76, 78, 58, 27, 34, 69, 34,  9,  3,
       77, 85, 92, 32, 67,  6, 27, 16, 90, 87, 44, 70, 50,  5, 63, 81, 67,
       67, 64, 20, 86, 29, 44, 58,  6, 51, 27, 79, 41, 70, 71, 91, 64, 11,
       68, 86, 12,  2, 83, 36, 23, 42, 25, 49, 43, 68,  8, 37, 76, 57, 34,
       77, 69, 34, 16, 70, 48, 22, 71,  2, 10, 49, 43])

In [31]:
array2 = np.random.randint(1,100, 80)
array2

array([41, 78, 74, 66, 64, 83, 67, 26, 22, 77, 69, 30, 15, 23,  4, 34, 37,
       25, 61, 79, 75, 59, 21, 83, 71, 29, 51, 70, 35, 92, 29, 77, 56, 47,
       93, 79, 86, 64, 45,  2, 18, 92,  8, 86, 51, 89, 96, 41, 78, 40, 81,
       77, 46, 45, 80, 58, 83, 33, 77, 47, 24, 23, 49, 40, 92, 38, 34, 89,
       42, 28, 91, 23, 52, 96, 72, 72,  6, 68, 73, 80])

* Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [32]:
array1 = np.unique(array1)
array1

array([ 2,  3,  5,  6,  8,  9, 10, 11, 12, 16, 20, 22, 23, 25, 26, 27, 29,
       32, 34, 36, 37, 41, 42, 43, 44, 48, 49, 50, 51, 57, 58, 63, 64, 67,
       68, 69, 70, 71, 74, 76, 77, 78, 79, 80, 81, 83, 85, 86, 87, 90, 91,
       92])

In [33]:
array1.size

52

In [34]:
array2 = np.unique(array2)
array2

array([ 2,  4,  6,  8, 15, 18, 21, 22, 23, 24, 25, 26, 28, 29, 30, 33, 34,
       35, 37, 38, 40, 41, 42, 45, 46, 47, 49, 51, 52, 56, 58, 59, 61, 64,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 77, 78, 79, 80, 81, 83, 86,
       89, 91, 92, 93, 96])

In [35]:
array2.size

56

* Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [36]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 3,  5,  9, 10, 11, 12, 16, 20, 27, 32, 36, 43, 44, 48, 50, 57, 63,
       76, 85, 87, 90])

* Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [37]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 4, 15, 18, 21, 24, 28, 30, 33, 35, 38, 40, 45, 46, 47, 52, 56, 59,
       61, 66, 72, 73, 75, 89, 93, 96])

* Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [39]:
array5 = np.intersect1d(array1, array2)
array5

array([ 2,  6,  8, 22, 23, 25, 26, 29, 34, 37, 41, 42, 49, 51, 58, 64, 67,
       68, 69, 70, 71, 74, 77, 78, 79, 80, 81, 83, 86, 91, 92])

* ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [40]:
array1.size

52

In [ ]:
# el array1 y el array2 fueron creados de forma aleatoria con las mismas condiciones
# el array1 tenía más elementos repetidos que el array2  np.unique(array1) > np.unique(array2)

In [41]:
array2.size

56

In [42]:
array3.size

21

In [ ]:
# el array3 contiene los elementos diferentes que tiene el array1 con respecto al array2. Osea los que solo están en array1

In [43]:
array4.size

25

In [ ]:
# el array4 contiene los elementos diferentes que tiene el array2 con respecto al array1. Osea los que solo están en array2
# Por lo tanto el array 2 tiene más elemetos únicos propios que el array1.  np.unique(array1) > np.unique(array2) -- (array4.size) - (array2.size) = 4

In [44]:
array5.size

31