1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
* El valor de la primera fila y la segunda columna.

In [2]:
# Importamos librerías
import numpy as np

In [11]:
# Creamos el array 
a2 = np.random.randint(1,10,(5,3))
a2

array([[1, 4, 1],
       [4, 9, 6],
       [4, 8, 8],
       [6, 6, 6],
       [4, 4, 7]])

In [12]:
#Extraemos el valor pedido
a2[0,1]

4

* Los valores de la segunda fila y las dos primeras columnas.

In [13]:
a2[1,:2]

array([4, 9])

* Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [14]:
a2[0::2,:]

array([[1, 4, 1],
       [4, 8, 8],
       [4, 4, 7]])

In [15]:
a2[::2] # también lo podemos extraer así

array([[1, 4, 1],
       [4, 8, 8],
       [4, 4, 7]])

* Extraed los valores que sean mayores que 0.5.

In [16]:
a2[a2>0.5]

array([1, 4, 1, 4, 9, 6, 4, 8, 8, 6, 6, 6, 4, 4, 7])

In [ ]:
# Como todos nuestros elementos son integers, nos extrae todos en un array de una dimension

In [24]:
# Nos creamos un nuevo array con numeros float para poder filtrar por esas condiciones
afloat = np.random.rand(5,3)
afloat

array([[0.99356336, 0.65621957, 0.86916786],
       [0.72181938, 0.77737752, 0.41030904],
       [0.97031859, 0.91386991, 0.20842074],
       [0.161051  , 0.70539386, 0.67666644],
       [0.05344992, 0.66691831, 0.83524446]])

* Extraed los valores menores que 0.2 o mayores que 0.5

In [27]:
# Usamos nuestro array de floats para ello
afloat[(afloat<0.2) | (afloat>0.5)]

array([0.99356336, 0.65621957, 0.86916786, 0.72181938, 0.77737752,
       0.97031859, 0.91386991, 0.161051  , 0.70539386, 0.67666644,
       0.05344992, 0.66691831, 0.83524446])

2. Cread dos array de tres dimensiones:

* El primero de 2 matrices, 5 filas y 3 columnas.

In [6]:
arr3_1 = np.random.randint(1,10,(2,5,3))
arr3_1

array([[[5, 9, 8],
        [9, 2, 5],
        [3, 1, 7],
        [6, 5, 6],
        [8, 3, 3]],

       [[8, 9, 3],
        [2, 1, 8],
        [2, 8, 6],
        [3, 9, 5],
        [4, 4, 1]]])

* El segundo de 3 matrices, 2 filas y 5 columnas

In [7]:
arr3_2 = np.random.randint(1,10,(3,2,5))
arr3_2

array([[[7, 9, 7, 6, 1],
        [2, 3, 8, 1, 8]],

       [[5, 5, 2, 2, 8],
        [3, 4, 8, 3, 4]],

       [[3, 2, 4, 4, 8],
        [7, 7, 2, 7, 1]]])

* Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [8]:
np.add(arr3_1, arr3_2)

# Sale el ValueError: 'operands could not be broadcast together with shapes (2,5,3) (3,2,5) '.
# No se pueden sumar matrices que no tengan la misma forma.

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

* Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
    * .reshape()
    * .transpose()
Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [9]:
# reshape
# Le pasamos las dimensiones que queremos que tenga nuestro primer array "arr3_1" 
# para que se pueda sumar al segundo array "arr3_2"
arr3_1_resh = arr3_1.reshape((3,2,5))
arr3_1_resh

array([[[5, 9, 8, 9, 2],
        [5, 3, 1, 7, 6]],

       [[5, 6, 8, 3, 3],
        [8, 9, 3, 2, 1]],

       [[8, 2, 8, 6, 3],
        [9, 5, 4, 4, 1]]])

In [10]:
# ahora sumamos
np.add(arr3_1_resh, arr3_2)

array([[[12, 18, 15, 15,  3],
        [ 7,  6,  9,  8, 14]],

       [[10, 11, 10,  5, 11],
        [11, 13, 11,  5,  5]],

       [[11,  4, 12, 10, 11],
        [16, 12,  6, 11,  2]]])

In [11]:
# Transpose
# El array "arr3_1" tiene las dimensiones (2, 5, 3)
# El array "arr3_2" tiene las dimensiones (3, 2, 5)

# El array traspuesto, que partirá del "arr3_1", tendrá las mismas dimensiones, pero en posiciones cambiadas (para ser como "arr3_2")
# Vamos a construir las posiciones nuevas del array3_1_trans (?,?,?)

                                                                            
# La dimension que arr3_1 tene en la poscicion 0 (el 2), arr3_2 la tiene en la posicion 1
# (Nuestro 0 tendrá que ir en la posición 1 del array traspuesto)
                    # posiciones iniciales(0,1,2) -- dimensiones iniciales(2,5,3)
                       #nueva posición    (?,0,?) -- dimension nueva      (?,2,?)

                                                                                                         
# La dimension que arr3_1 tene en la poscicion 1 (el 5), arr3_2 la tiene en la posicion 2 

                    # posiciones iniciales(0,1,2) -- dimensiones iniciales(2,5,3)
                       #nueva posición    (?,0,1) -- dimension nueva      (?,2,5)

# La dimension que arr3_1 tene en la poscicion 2 (el 3), arr3_2 la tiene en la posicion 0 
# (Nuestro 2 tendrá que ir en la posición 0 del array traspuesto)
                    # posiciones iniciales(0,1,2) -- dimensiones iniciales(2,5,3)
                       #nueva posición    (2,0,1) -- dimension nueva      (3,2,5) -- que es igual a la dimension de arr3_2, ¡las podemos sumar!

#arr3_1_trans tendrá las dimensiones del array original, pero con las posiciones en este orden -- (2, 0, 1)


arr3_1       # (0, 1, 2)
             # (2, 5, 3)        
                   

array([[[5, 9, 8],
        [9, 2, 5],
        [3, 1, 7],
        [6, 5, 6],
        [8, 3, 3]],

       [[8, 9, 3],
        [2, 1, 8],
        [2, 8, 6],
        [3, 9, 5],
        [4, 4, 1]]])

In [12]:
arr3_2      # (0, 1, 2)
            # (3, 2, 5)

array([[[7, 9, 7, 6, 1],
        [2, 3, 8, 1, 8]],

       [[5, 5, 2, 2, 8],
        [3, 4, 8, 3, 4]],

       [[3, 2, 4, 4, 8],
        [7, 7, 2, 7, 1]]])

In [13]:
arr3_1_trans = arr3_1.transpose((2, 0, 1))
arr3_1_trans

array([[[5, 9, 3, 6, 8],
        [8, 2, 2, 3, 4]],

       [[9, 2, 1, 5, 3],
        [9, 1, 8, 9, 4]],

       [[8, 5, 7, 6, 3],
        [3, 8, 6, 5, 1]]])

In [14]:
np.add(arr3_1_trans,arr3_2)

array([[[12, 18, 10, 12,  9],
        [10,  5, 10,  4, 12]],

       [[14,  7,  3,  7, 11],
        [12,  5, 16, 12,  8]],

       [[11,  7, 11, 10, 11],
        [10, 15,  8, 12,  2]]])