1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota
* El array de 2 dimensiones debe ser de 2 filas y 3 columnas
* El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [41]:
import numpy as np

In [42]:
a1 = np.random.rand(2)
a2 = np.random.rand(2,3)
a3 = np.random.rand(2,3,5)

In [43]:
a1

array([0.20349601, 0.63134759])

In [44]:
a2

array([[0.08628814, 0.72072605, 0.67036131],
       [0.58440612, 0.66813976, 0.3757746 ]])

In [45]:
a3

array([[[0.89457292, 0.18303206, 0.68476245, 0.93759513, 0.83919331],
        [0.21028486, 0.22026377, 0.02874689, 0.02643883, 0.79020775],
        [0.37010499, 0.60718987, 0.87348024, 0.59222492, 0.39365621]],

       [[0.42708101, 0.52901705, 0.96753858, 0.73668901, 0.95215725],
        [0.59730392, 0.98967435, 0.44293459, 0.485005  , 0.60758299],
        [0.65405183, 0.36185767, 0.40246233, 0.68849411, 0.90152511]]])

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [46]:
# forma
a1.shape

(2,)

In [47]:
a2.shape

(2, 3)

In [48]:
a3.shape

(2, 3, 5)

In [49]:
# tamaño (número de elementos)
a1.size

2

In [50]:
a2.size

6

In [51]:
a3.size

30

In [52]:
# dimensiones
a1.ndim

1

In [53]:
a2.ndim

2

In [54]:
a3.ndim

3

In [55]:
# tipo de datos que contienen
a1.dtype

dtype('float64')

In [56]:
a2.dtype

dtype('float64')

In [57]:
a3.dtype

dtype('float64')

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [58]:
a_id = np.identity(3)
a_id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [59]:
a_ones = np.ones_like(a3)
a_ones

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

5. Es el momento de hacer algunas operaciones entre arrays
* ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

In [60]:
a2 + a_id

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
suma = np.add(a2, a_id)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
# No se pueden sumar, porque no tienen la misma forma: 'ValueError: operands could not be broadcast together with shapes (2,3) (3,3)'

* En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [61]:
# Como entendermos que queremos conservar la matriz identidad como sumando, podemos crear una matriz a semejanza de a_id:
a4 = np.empty_like(a_id)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
a4 + a_id

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [63]:
# O podemos crear una matriz aleatoria con las dimensiones de a_id:

a5 = np.random.randint(0,15, (3,3))
a5

array([[ 4,  0,  6],
       [11,  4, 12],
       [ 0,  4,  3]])

In [64]:
np.add(a5, a_id)

array([[ 5.,  0.,  6.],
       [11.,  5., 12.],
       [ 0.,  4.,  4.]])

* Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [65]:
a_id * a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.multiply(a_id, a4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#EXTRA
# probamos a multiplicar a_id con la matriz a2, ya que el producto matricial se puede hacer cuando las matrices tienen el numero de filas = numero de columnas de la otra
a_id * a2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
# probamos lo que dijimios en clase:
# si coinciden el numero de columnas de a_id con el numero de filas de otra matriz, ¿se pueden multiplicar?
# creamos nueva matriz con el mismo numero de filas que columnas tiene a_id
a6 = np.random.rand(3,4)
a6

array([[0.49810236, 0.13777818, 0.1443404 , 0.99090662],
       [0.18733741, 0.56218448, 0.8790324 , 0.84011391],
       [0.64462216, 0.84181708, 0.79168302, 0.24842595]])

In [ ]:
a6 * a_id

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [ ]:
# ¿y si cada una tiene el numero de filas igual al numero de columnas de la otra?
ap = np.random.randint(0,3,(3,4))
ap2 = np.random.randint(0,3,(4,3))

ap * ap2


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
# CONCLUSION lo que dijimos en clase no está funcionando
# El producto matricial no es lo mismo que np.multiply. 
# np.multiply nos está multiplicando elemento a elemento, para el producto matricial usaremos el np.dot()

* Dividid las dos matrices

In [ ]:
a_id / a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.divide(a_id, a4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])