 1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [2]:
import numpy as np

In [38]:
arr = np.random.rand(2,3,5).round(decimals = 1)
arr

array([[[0.2, 0.7, 1. , 0.8, 0.1],
        [0.6, 0.7, 0.7, 0.9, 0.1],
        [0.5, 0.5, 0.6, 0.3, 0.7]],

       [[0.3, 1. , 0.8, 0.9, 0.1],
        [0.2, 0.2, 0.4, 0.5, 0.3],
        [0.5, 0.4, 0.6, 0.7, 0.7]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal

In [39]:
arr_media = np.mean(arr).round(decimals = 1)
arr_media

0.5

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [40]:
arr_max = np.max(arr)
arr_max

1.0

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal

In [41]:
arr_min = np.min(arr)
arr_min

0.1

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".


In [42]:
# creamos un array vacio de mismas caracteristicas que el anterior
array = np.empty_like(arr, dtype= str)
array

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [43]:
# El array tiene que ser string para que podamos sustituirlo por letras.

In [50]:
arr

array([[[0.2, 0.7, 1. , 0.8, 0.1],
        [0.6, 0.7, 0.7, 0.9, 0.1],
        [0.5, 0.5, 0.6, 0.3, 0.7]],

       [[0.3, 1. , 0.8, 0.9, 0.1],
        [0.2, 0.2, 0.4, 0.5, 0.3],
        [0.5, 0.4, 0.6, 0.7, 0.7]]])

In [52]:
# Iteramos por el array
for i in range(arr.shape[0]):
    
    for j in range(arr.shape[1]):
        
        for k in range(arr.shape[2]):
           
            if arr[i][j][k] == arr_media:
                array[i][j][k] = 'A'
            elif arr[i][j][k]  == arr_max:
                array[i][j][k] = 'D'
            elif arr[i][j][k]  == arr_min:          # ponemos estas condiciones primero y luego, si no coinciden, chequeamos si cumplen las de más abajo
                array[i][j][k] = 'E'
            elif arr[i][j][k]  > arr_media:
                array[i][j][k] = 'B'
            elif arr[i][j][k]  < arr_media:
                array[i][j][k] = 'C'
            
            

array
            

array([[['C', 'B', 'D', 'B', 'E'],
        ['B', 'B', 'B', 'B', 'E'],
        ['A', 'A', 'B', 'C', 'B']],

       [['C', 'D', 'B', 'B', 'E'],
        ['C', 'C', 'C', 'A', 'C'],
        ['A', 'C', 'B', 'B', 'B']]], dtype='<U1')

6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:
* Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
* Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
* Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.


In [63]:
# Para poder iterar por ambos arrays, hacemos un reshape al array anterior
arr2 = array.reshape(30)
arr2

array(['C', 'B', 'D', 'B', 'E', 'B', 'B', 'B', 'B', 'E', 'A', 'A', 'B',
       'C', 'B', 'C', 'D', 'B', 'B', 'E', 'C', 'C', 'C', 'A', 'C', 'A',
       'C', 'B', 'B', 'B'], dtype='<U1')

In [53]:
array_1d = np.empty(30, dtype = int )
array_1d

array([4596373779694328218, 4604480259023595110, 4607182418800017408,
       4605380978949069210, 4591870180066957722, 4603579539098121011,
       4604480259023595110, 4604480259023595110, 4606281698874543309,
       4591870180066957722, 4602678819172646912, 4602678819172646912,
       4603579539098121011, 4599075939470750515, 4604480259023595110,
       4599075939470750515, 4607182418800017408, 4605380978949069210,
       4606281698874543309, 4591870180066957722, 4596373779694328218,
       4596373779694328218, 4600877379321698714, 4602678819172646912,
       4599075939470750515, 4602678819172646912, 4600877379321698714,
       4603579539098121011, 4604480259023595110, 4604480259023595110])

In [64]:
for x in range(array_1d.size):

    if arr2[x] == 'A' or arr2[x] == 'B':
        array_1d[x] = 1
    elif arr2[x]  == 'C' or arr2[x] == 'D':
        array_1d[x] = 2
    elif arr2[x]  == 'E':        
        array_1d[x] = 3
array_1d

array([2, 1, 2, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 2, 1, 2, 2, 1, 1, 3, 2, 2,
       2, 1, 2, 1, 2, 1, 1, 1])

In [65]:
arr3 = array_1d.reshape(2,3,5)
arr3

array([[[2, 1, 2, 1, 3],
        [1, 1, 1, 1, 3],
        [1, 1, 1, 2, 1]],

       [[2, 2, 1, 1, 3],
        [2, 2, 2, 1, 2],
        [1, 2, 1, 1, 1]]])