 1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [1]:
import numpy as np

In [38]:
arr_3 = np.random.rand(2,3,5).round(decimals = 1)
arr_3

array([[[0.7, 0.3, 0.6, 0.9, 0.1],
        [0.5, 0.8, 0.3, 0.5, 0.9],
        [0.5, 0.5, 0.3, 0.7, 0.7]],

       [[0.6, 0.8, 0.3, 0.2, 0.7],
        [0.5, 0.9, 0.2, 0.7, 0.6],
        [0.1, 0.9, 0.1, 0.6, 0.6]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal

In [5]:
arr_3_media = np.mean(arr_3).round(decimals= 1)
arr_3_media

0.5

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [6]:
arr_3_max = np.max(arr_3)
arr_3_max

1.0

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal

In [7]:
arr_3_min = np.min(arr_3)
arr_3_min

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".


In [34]:
# creamos un array vacio de mismas caracteristicas que el anterior
array = np.empty_like(arr_3)
array

array([[[2. , 0.5, 1. , 0.5, 0.2],
        [0.5, 0.7, 0.8, 0.9, 0.4],
        [0.1, 0.4, 0.6, 0.7, 0.8]],

       [[0.4, 0.5, 0.5, 0.4, 0.6],
        [0.9, 0.6, 0.1, 0. , 0.5],
        [0.3, 0.6, 0.7, 0.3, 0.5]]])

In [35]:
np.where(array == arr_3_media)

(array([0, 0, 0, 1, 1, 1, 1]),
 array([0, 0, 1, 0, 0, 1, 2]),
 array([1, 3, 0, 1, 2, 4, 4]))

In [29]:
array.replace(np.where(array == arr_3_media), 1.8)

AttributeError: 'numpy.ndarray' object has no attribute 'replace'

In [19]:
lista = ['a', 'b', 'c']

In [20]:
lista[0]

'a'

In [21]:
lista.index('a')

0

In [22]:
lista[lista.index('a')]

'a'

In [18]:
np.array(2)

array(2)

In [13]:
contador = 0
while contador < array.size:
    for elem in array:
        array[contador, ] = str(elem)
    array

array([[[2. , 0.5, 1. , 0.5, 0.2],
        [0.5, 0.7, 0.8, 0.9, 0.4],
        [0.1, 0.4, 0.6, 0.7, 0.8]],

       [[0.4, 0.5, 0.5, 0.4, 0.6],
        [0.9, 0.6, 0.1, 0. , 0.5],
        [0.3, 0.6, 0.7, 0.3, 0.5]]])

In [15]:
array_str = str(array)
array_str

'[[[2.  0.5 1.  0.5 0.2]\n  [0.5 0.7 0.8 0.9 0.4]\n  [0.1 0.4 0.6 0.7 0.8]]\n\n [[0.4 0.5 0.5 0.4 0.6]\n  [0.9 0.6 0.1 0.  0.5]\n  [0.3 0.6 0.7 0.3 0.5]]]'

In [14]:
a_str = np.array(['a','b', 'c'])
a_str

array(['a', 'b', 'c'], dtype='<U1')

In [10]:
# reemplazamos los valores de la matriz vacia
for a in array:
    array[array == arr_3_media] = "A"
    
        

ValueError: could not convert string to float: 'A'